### ISSUE TITLE
ورژن لاراول

### ISSUE THREAD

**Issue by alinasiri1367** [larabook/gateway#10]
سلام
برا کدام ورژن از لاراول مناسبه؟
 gateway من رو 5.2 نصب کردم ولی هنگام تغییر فایل انگار 
رو نمیشناسه
config/app.php

**Comment by hpakdaman** [comment]
ببنید 
vendor/larabook
موجوده ؟ 

اگر نبود مجددا با این دستور نصبش کنید .
composer require larabook/gateway

**Comment by alinasiri1367** [comment]
الان فایل 
config/gateway.php
انجام نمیشه

**Comment by hpakdaman** [comment]
[http://prnt.sc/b56046](url)
