### ISSUE TITLE
اضافه نشدن payir

### ISSUE THREAD

**Issue by SajjadKharrazi** [larabook/gateway#106]
آقا هنوز درگاه پی دات آی آر رو درست اضافه نکردید و فانکشن ها و متدهاش کامل نشده
ولی توی داکیومنت نوشتید که اضافه شده؟
چه کاریه آخه؟

PAYIR (NEW)

**Comment by hpakdaman** [comment]
شما باید نسخه دولوپ رو استفاده میکردید

**Comment by SajjadKharrazi** [comment]
فرقی نداره
اون هم ناقصه

**Comment by hpakdaman** [comment]
الان روی نسخه اصلی هم اضافه کردم تغییرات رو با دستور 
composer update larabook/gateway
باید بتونید آپدیت جدید رو بگیرید

**Comment by SajjadKharrazi** [comment]
نکته اصلی اینجاس که:
https://github.com/larabook/gateway/blob/c16f8c10cf47b41ebb23bf354cd06d5b3bfd97cf/src/Payir/Payir.php#L115

تابع رو کال میکنید ولی همچین تابعی وجود نداره
من خودم تغییرات رو دادم و اصلاح کردم و دارم استفاده میکنم ازش
در کل ممنون از زحمات

**Comment by hpakdaman** [comment]
درسته . اصلاحش میکنم . این تابع باید $this->newTransaction() باشه

**Comment by SajjadKharrazi** [comment]
بله دقیقا
نکته دیگه ای هم که دوست داشتم بدونید و اصلاح کنید اینه که توی این خطر
https://github.com/larabook/gateway/blob/c16f8c10cf47b41ebb23bf354cd06d5b3bfd97cf/src/Payir/Payir.php#L119

پورت رو از یو آر ال حذف میکنه گویا
من خودم تغییر دادم و مستقیم از $this->callbackUrl استفاده کردم

متدی که براش نوشتید درست عمل نمیکنه
localhost:8000 ro mikone localhost

**Comment by hpakdaman** [comment]
این مشکل هم برطرف شد.

**Comment by hpakdaman** [comment]
آپدیت کنید به 3.3.2
