### ISSUE TITLE
مشکل exception بانک ملت

### ISSUE THREAD

**Issue by Nimapcart** [larabook/gateway#107]
با سلام و خسته نباشید

من با خطاهای بانک ملت مشکل دارم که تمام خطاهارو تو صفحه ارور لاراول نمایش میده. نسخه لاراول هم 5.5 هست.
به هر شکلی هم نوشتم عمل نکرد. نمونه ها:

catch (\Larabookir\Gateway\Mellat\MellatException $e) 
catch (\MellatException $e) 
catch (MellatException $e) 

لطفا در این مورد راهنمایی بفرمایید. باتشکر

**Comment by hpakdaman** [comment]
با سلام . 
از
\Exception 
استفاده کنید

**Comment by Nimapcart** [comment]
![capture](https://user-images.githubusercontent.com/31618750/36719348-11ae12aa-1bba-11e8-8994-846195cd0edb.PNG)

متاسفانه همچنان همین ارور رو میده

**Comment by hpakdaman** [comment]
مبلغ را چند وارد کرده اید ؟‌ 
بالای ۱۰۰ تومان وارد کنید

**Comment by Nimapcart** [comment]
خودم مخصوصا به این شکل وارد کردم. منظورم اینه که اگه این کد خطا رو به ویو من نفرسته، خب بقیه کدهارو هم نمیفرسته. درسته؟

**Comment by hpakdaman** [comment]
بله نمیفرسته . لطفا از کد های ارسال درخواستتون اسکرین شات بفرستید

**Comment by Nimapcart** [comment]
خدمت شما

![capture](https://user-images.githubusercontent.com/31618750/36720856-6eeefc28-1bbe-11e8-810c-cc9edfdd5a3b.PNG)

بعد از قسمت try هستش

**Comment by hpakdaman** [comment]
چیزی که مشخص است اینه که اکسپشن توسط 
catch
دریافت نمیشه . 
یه مقدار مستندات لاراول ۵ .۵ رو بخونید بنظرم بخاطر تغییرات این نسخه باشه .
توی حالت
debug=false
هم چک کنید .

**Comment by hpakdaman** [comment]
همه اکسپشن ها رو پاک کنید فقط از 
\Exception 
استفاده کنید. 

این دستورات رو در  مسیر کنترلر نوشته اید یا  توی روت هاتون ؟

**Comment by hpakdaman** [comment]
بالای صفحه 
use Exception;
رو بنویسید .

اگر نشد از این اکسپشن هم استفاده کنید :‌
RuntimeException

**Comment by Nimapcart** [comment]
ممنون از توجهتون. البته باید بگم که 
RetryException
بخوبی کار میکنه. پس احتمالا مشکل از 
catch
نیست.

با اضافه کردن namespace
دیگه صفحه ارور نمیاد و فقط مقدار رو نمایش میده به شکل زیر

![capture](https://user-images.githubusercontent.com/31618750/36722334-7fe9b7a8-1bc2-11e8-86d2-a0563820f7c1.PNG)

ولی همچنان نمیفرسته داخل ویو که نشون میده بازم نمیره داخل 
catch
مورد نظر.

RuntimeException هم تفاوتی ایجاد نکرد

**Comment by Nimapcart** [comment]
با debug = false

هم کلا هیچی نمیاره

**Comment by Nimapcart** [comment]
پرسیده بودین تو روت ها هست یا کنترلر ، یادم رفت بگم 

داخل کنترلر هستن

**Comment by Nimapcart** [comment]
و اینکه این مشکل فقط تو بانک ملت نیست. تو باقی بانک ها هم هست با کد ارورهای مختلف

**Comment by hpakdaman** [comment]
ممکنه بخاطر تنظیمات پی اچ پی تون باشه ؟
اگر ویندوز دارید از چی استفاده میکنید ؟‌ ومپ یا زمپ
روی سرور تست کردید ؟‌

**Comment by Nimapcart** [comment]
روی سرور هستم. روی لوکال که این درگاه ها به خاطر آی پی کار نمیکنن

**Comment by hpakdaman** [comment]
این مشکلتون متاسفانه مربوط به تنظیمات پی اچ پی تون ظاهرن است و مرتبط با درگاه نمیشه . 
باید خودتون دستکاریش کنید و حلش کنید
امیدوارم موفق باشید

**Comment by Nimapcart** [comment]
آقای پاکدامن ضمن تشکر از شما و پیگیریتون. جا داره معذرت بخوام چرا که مشکل از خودم بود و بسیار هم ناشیانه بود. من اکسپشن هارو فقط در برگشت از بانک قرار داده بودم و در زمان ارسال به بانک اکسپشن نداشتم.

باز هم ممنونم.
