### ISSUE TITLE
بانک سپه

### ISSUE THREAD

**Issue by SajjadKharrazi** [larabook/gateway#108]
درگاه بانک سپه که جدیدا درست کرده رو هم اگه به پکیج اضافه کنی خیلی خوب میشه

**Comment by hpakdaman** [comment]
درگاه سپه رو نوشته ام فرصت کنم اضافه خواهم کرد

**Comment by hpakdaman** [comment]
سپه رو کی درست کرده  ؟‌

**Comment by hpakdaman** [comment]
انشالله بزودی اضافه میکنیم .
