### ISSUE TITLE
دریافت زمان پرداخت

### ISSUE THREAD

**Issue by Nimapcart** [larabook/gateway#109]
با سلام مجدد

آیا امکان دریافت زمان پرداخت و نمایش آن، بدون انجام رکوئست اضافی به دیتابیس امکانپذیر هست؟

مثلا یه همچین چیزی:

$gateway->payTime();

**Comment by hpakdaman** [comment]
با سلام . متاسفانه همچین چیزی توی بانک های ایرانی تعبیه نشه است .
