### ISSUE TITLE
مشکل با درگاه زرین پال

### ISSUE THREAD

**Issue by alinasiri1367** [larabook/gateway#11]
هنگام فراخوانی جهت اتصال به درگاه زرین پال
`$gateway = Gateway::make(new Larabookir\Gateway\Zarinpal\Zarinpal());`
یه پیغام میده مبنی بر اینکه باید پارامتر های کلاس رو وارد نمایید؟

> Missing argument 1 for Larabookir\Gateway\Zarinpal\Zarinpal::__construct(), called in /home/airmall/domains/domains.ir/public_html/laravel/app/Http/routes.php on line 13 and defined

الان مشکل چیه؟

**Comment by hpakdaman** [comment]
مشکل حل شد

سه تا فایل تغییر داده شد

- /src/Zarinpal/Zarinpal.php
- /src/PortAbstract.php
- /src/GatewayResolver.php

**Comment by mehrdadshirvan** [comment]
سلام برای درگاه پاسارگاد مشکل دارم
`
try {
            $gateway = \Gateway::pasargad();
            $gateway->setCallback($back_url);
            $gateway->price($final_price_rial)->ready();
            $refId =  $gateway->refId();
            $transID = $gateway->transactionId();

            return $gateway->redirect();
        } catch (Exception $e) {
            echo $e->getMessage();
        }
`
عرور اینه
`Declaration of Larabookir\Gateway\Pasargad\Pasargad::ready($payment_id, $callback_url) must be compatible with Larabookir\Gateway\PortInterface::ready()`

**Comment by hamed-ehtesham** [comment]
```php
$gateway = \Gateway::pasargad();
```
این اشتباه هست باید به شکل زیر بنویسید

```php
$gateway = \Gateway::make(new \Pasargad());
```

**Comment by mehrdadshirvan** [comment]
> ```
> $gateway = \Gateway::pasargad();
> ```
> 
> این اشتباه هست باید به شکل زیر بنویسید
> 
> ```
> $gateway = \Gateway::make(new \Pasargad());
> ```

الان عرور اینو میده میگه نمیشناسه کلاسشو

Class 'Pasargad' not found

**Comment by mehrdadshirvan** [comment]
سلام برای درگاه پاسارگاد مشکل دارم

میره رو درگاه ولی عرور میده  

> خطا در ارسال اطلاعات

در ابتدا عرور این بود که نمیرفت رو درگاه 

`Declaration of Larabookir\Gateway\Pasargad\Pasargad::ready($payment_id, $callback_url) must be compatible with Larabookir\Gateway\PortInterface::ready()`

بعد تابع 

```
public function ready($payment_id, $callback_url)
    {
        $this->sendPayRequest($payment_id, $callback_url);

        return $this;
    }
```

رو کامنت کردم و اینو نوشتم و رفت رو درگاه اما عرور اینه الان 

```
public function ready()
    {
        return $this;
    }
```

عروری که درگاه میده 
> خطا در ارسال اطلاعات

هم کد خصوصی و مرچند کد و شماره ترمینال ارسال میشه به درگاه

**Comment by hamed-ehtesham** [comment]
> > ```
> > $gateway = \Gateway::pasargad();
> > ```
> > 
> > 
> > این اشتباه هست باید به شکل زیر بنویسید
> > ```
> > $gateway = \Gateway::make(new \Pasargad());
> > ```
> 
> الان عرور اینو میده میگه نمیشناسه کلاسشو
> 
> Class 'Pasargad' not found

خب کلاس رو
import
کنید تا بشناسه

در ضمن در مورد کامنت بعدی که نوشتید باید بگم کدهای کلاس رو دستکاری نکنید!!

**Comment by mahdidoraj** [comment]
سلام
بنده هم همین مشکل رو دارم و زمانی که کلاس رو هم 
import
میکنم بازم خطا میده!
متن خطا
Declaration of Larabookir\Gateway\Pasargad\Pasargad::ready($payment_id, $callback_url) must be compatible with Larabookir\Gateway\PortInterface::ready()

**Comment by sevdasa** [comment]
$gateway = Gateway::make(new Zarinpal());
من اینو میسازم ارور میده
strtoupper() expects parameter 1 to be string, object given
