### ISSUE TITLE
تراکنش سامان موفق ولی refid و tracking code null هستند !!!!!

### ISSUE THREAD

**Issue by mrarteh** [larabook/gateway#131]
سلام دوستان،ممنونم از پکیج به این قدرت.من با زرین پال استفاده میکردم هیچ مشکلی نداشتم ولی به تازگی با بانک سامان به مشکل خوردم شدیدا.کمکم میکنید لطفا؟
مشکل اینه که من فقط transaction id دارم
و هیچ کدوم tracking code  و refid  و cardnumber null هست کلا

**Comment by mrarteh** [comment]
![photo_ - - _ - -](https://user-images.githubusercontent.com/18173488/43223040-148d7f84-9067-11e8-9528-b338dcf4bde3.jpg)

**Comment by mrarteh** [comment]
$gateway = Gateway::saman();
            $gateway->setCallback(url('/callback/bank'));

            $gateway->price($totall)->ready();



            $refId = $gateway->refId();
            $transID = $gateway->transactionId();
            return $gateway->redirect();

کالبک
 $gateway = Gateway::verify();
            $trackingCode = $gateway->trackingCode();
            $refId = $gateway->refId();
            $cardNumber = $gateway->cardNumber();

            $transID = $gateway->transactionId();

**Comment by mrarteh** [comment]
اینجوری هم که میگیرمشون null هستن

**Comment by mrarteh** [comment]
tracking code رو درستش کردم ولی هرکاری میکنم refid نال هست

**Comment by davoudrafati** [comment]
چجوری درستش کردی 
منم همین مشکل رو دارم
همه فیلد های بانک سامان خالیه

**Comment by AGhasemzadeh** [comment]
سلام
@davoudrafati 
shirazsoft/gateway

**Comment by mrarteh** [comment]
<?php

namespace Larabookir\Gateway\Saman;

use Illuminate\Support\Facades\Input;
use SoapClient;
use Larabookir\Gateway\PortAbstract;
use Larabookir\Gateway\PortInterface;

class Saman extends PortAbstract implements PortInterface
{
    /**
     * Address of main SOAP server
     *
     * @var string
     */
    protected $serverUrl = 'https://sep.shaparak.ir/payments/referencepayment.asmx?wsdl';

    /**
     * {@inheritdoc}
     */
    public function set($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function ready()
    {
        $this->newTransaction();

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function redirect()
    {

        return \View::make('gateway::saman-redirector')->with([
            'amount' => $this->amount,
            'merchant' => $this->config->get('gateway.saman.merchant'),
            'resNum' => $this->transactionId(),
            'callBackUrl' => $this->getCallback()
        ]);
    }

  
    /**
     * {@inheritdoc}
     */
    public function verify($transaction)
    {
        parent::verify($transaction);

        $this->userPayment();
        $this->verifyPayment();

        return $this;
    }

    /**
     * Sets callback url
     * @param $url
     */
    function setCallback($url)
    {
        $this->callbackUrl = $url;
        return $this;
    }

    /**
     * Gets callback url
     * @return string
     */
    function getCallback()
    {
        if (!$this->callbackUrl)
            $this->callbackUrl = $this->config->get('gateway.saman.callback-url');

        $url = $this->makeCallback($this->callbackUrl, ['transaction_id' => $this->transactionId()]);

        return $url;
    }


    /**
     * Check user payment
     *
     * @return bool
     *
     * @throws SamanException
     */
    protected function userPayment()
    {
        $this->refId = Input::get('RefNum');
        $this->trackingCode = Input::get('TRACENO');
        $this->cardNumber = Input::get('‫‪SecurePan‬‬');
        $payRequestRes = Input::get('State');
        $payRequestResCode = Input::get('StateCode');


        if ($payRequestRes == 'OK') {
            return true;
        }

        $this->transactionFailed();
        $this->newLog($payRequestResCode, @SamanException::$errors[$payRequestRes]);
        throw new SamanException($payRequestRes);
    }


    /**
     * Verify user payment from bank server
     *
     * @return bool
     *
     * @throws SamanException
     * @throws SoapFault
     */
    protected function verifyPayment()
    {
        $fields = array(
            "merchantID" => $this->config->get('gateway.saman.merchant'),
            "RefNum" => $this->refId,
            "password" => $this->config->get('gateway.saman.password'),
        );


        try {
            $soap = new SoapClient($this->serverUrl);
            $response = $soap->VerifyTransaction($fields["RefNum"], $fields["merchantID"]);

        } catch (\SoapFault $e) {
            $this->transactionFailed();
            $this->newLog('SoapFault', $e->getMessage());
            throw $e;
        }

        $response = intval($response);

        if ($response == $this->amount) {
            $this->transactionSucceed();
            return true;
        }

        //Reverse Transaction
        if($response>0){
            try {
                $soap = new SoapClient($this->serverUrl);
                $response = $soap->ReverseTransaction($fields["RefNum"], $fields["merchantID"], $fields["password"], $response);

            } catch (\SoapFault $e) {
                $this->transactionFailed();
                $this->newLog('SoapFault', $e->getMessage());
                throw $e;
            }
        }

        //
        $this->transactionFailed();
        $this->newLog($response, SamanException::$errors[$response]);
        throw new SamanException($response);



    }


}

**Comment by mrarteh** [comment]
`<?php

namespace Larabookir\Gateway\Saman;

use Illuminate\Support\Facades\Input;
use SoapClient;
use Larabookir\Gateway\PortAbstract;
use Larabookir\Gateway\PortInterface;

class Saman extends PortAbstract implements PortInterface
{
    /**
     * Address of main SOAP server
     *
     * @var string
     */
    protected $serverUrl = 'https://sep.shaparak.ir/payments/referencepayment.asmx?wsdl';

    /**
     * {@inheritdoc}
     */
    public function set($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function ready()
    {
        $this->newTransaction();

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function redirect()
    {

        return \View::make('gateway::saman-redirector')->with([
            'amount' => $this->amount,
            'merchant' => $this->config->get('gateway.saman.merchant'),
            'resNum' => $this->transactionId(),
            'callBackUrl' => $this->getCallback()
        ]);
    }

  
    /**
     * {@inheritdoc}
     */
    public function verify($transaction)
    {
        parent::verify($transaction);

        $this->userPayment();
        $this->verifyPayment();

        return $this;
    }

    /**
     * Sets callback url
     * @param $url
     */
    function setCallback($url)
    {
        $this->callbackUrl = $url;
        return $this;
    }

    /**
     * Gets callback url
     * @return string
     */
    function getCallback()
    {
        if (!$this->callbackUrl)
            $this->callbackUrl = $this->config->get('gateway.saman.callback-url');

        $url = $this->makeCallback($this->callbackUrl, ['transaction_id' => $this->transactionId()]);

        return $url;
    }


    /**
     * Check user payment
     *
     * @return bool
     *
     * @throws SamanException
     */
    protected function userPayment()
    {
        $this->refId = Input::get('RefNum');
        $this->trackingCode = Input::get('TRACENO');
        $this->cardNumber = Input::get('‫‪SecurePan‬‬');
        $payRequestRes = Input::get('State');
        $payRequestResCode = Input::get('StateCode');


        if ($payRequestRes == 'OK') {
            return true;
        }

        $this->transactionFailed();
        $this->newLog($payRequestResCode, @SamanException::$errors[$payRequestRes]);
        throw new SamanException($payRequestRes);
    }


    /**
     * Verify user payment from bank server
     *
     * @return bool
     *
     * @throws SamanException
     * @throws SoapFault
     */
    protected function verifyPayment()
    {
        $fields = array(
            "merchantID" => $this->config->get('gateway.saman.merchant'),
            "RefNum" => $this->refId,
            "password" => $this->config->get('gateway.saman.password'),
        );


        try {
            $soap = new SoapClient($this->serverUrl);
            $response = $soap->VerifyTransaction($fields["RefNum"], $fields["merchantID"]);

        } catch (\SoapFault $e) {
            $this->transactionFailed();
            $this->newLog('SoapFault', $e->getMessage());
            throw $e;
        }

        $response = intval($response);

        if ($response == $this->amount) {
            $this->transactionSucceed();
            return true;
        }

        //Reverse Transaction
        if($response>0){
            try {
                $soap = new SoapClient($this->serverUrl);
                $response = $soap->ReverseTransaction($fields["RefNum"], $fields["merchantID"], $fields["password"], $response);

            } catch (\SoapFault $e) {
                $this->transactionFailed();
                $this->newLog('SoapFault', $e->getMessage());
                throw $e;
            }
        }

        //
        $this->transactionFailed();
        $this->newLog($response, SamanException::$errors[$response]);
        throw new SamanException($response);



    }


}
`

**Comment by mrarteh** [comment]
من مشکل ترکینگ کد رو حل کردم.الان درست کار میکنه درگاه ولی رف ایدی رو نال میده هنوز درست نتونستم بکنم

**Comment by AGhasemzadeh** [comment]
@davoudrafati
خیر پروژه ما مواردی دارد که در این بسته نیست لذا نمی تونشتیم یکی کنیم.

**Comment by hpakdaman** [comment]
سلام  . از اونجایی که درگاه بانک سامان ندارم سخت هست دیباگ کردن و برطرف کردن مشکلش . 

حاضر هستید دسترسی بدید تا مشکل رو برطرف کنم بنده ؟

**Comment by mohammad6006** [comment]
بانک سامان رف آی دی رو بعد از پرداخت موفق برمیگردونه

این نمونه ای از کالبک موفق در بانک سامان هست 

![image](https://user-images.githubusercontent.com/553379/45265744-5248cf00-b465-11e8-9d61-eca28bc0b8e3.png)
این هم نمونه ناموفق
![image](https://user-images.githubusercontent.com/553379/45265752-6d1b4380-b465-11e8-90f4-902b4d472253.png)

**Comment by mostafaznv** [comment]
منم همچین مشکلی رو دارم.
