### ISSUE TITLE
بروزرسانی درگاه پارسیان

### ISSUE THREAD

**Issue by mohammad-69** [larabook/gateway#134]
سلام وقت بخیر

ممنون از زحمات شما اما متاسفانه به تازگی پارسیان درگاه هاشو اپدیت کرده و دیگه کد درگاه پارسیان کار نمیکنه 
میخواستم لطف کنین و درگاه پارسیان رو اپدیت کنید تا بقیه همکاران و دوستان هم اگر به مشکل مشابه بنده برخورد کردند با مراجعه با پکیج شما مشکلشون رفع شه. 

باتشکرو سپاس

**Comment by sjys** [comment]
منم این مشکل رو دارم شما چطوری حلش کردید؟

**Comment by mohammad-69** [comment]
@sjys یکی از دوستان این مشکل رو رفع کردند به 
issue parsian new gateway method  
مراجعه کنین آقای ولی پور کدشو ریفکتور کردن

**Comment by sjys** [comment]
ممنون

**Comment by mohammad-69** [comment]
خواهش میکنم

**Comment by hpakdaman** [comment]
سلام .  
پول رکويست کردن ؟‌

**Comment by mohammad-69** [comment]
> سلام .
> پول رکويست کردن ؟‌

توی pull request ها که چیزی نیستش
