### ISSUE TITLE
کنسل کردن پرداخت بعد از verify

### ISSUE THREAD

**Issue by 96rajabi** [larabook/gateway#135]
خسته نباشید دوستان آیا این امکان هست که ما بعد از 
verify
کردن پرداخت 
اون رو مجددا کنسل کنیم تا پول به حساب مشتری برگرده برای زمان هایی که خطا های خاص رخ میده ؟؟؟

**Comment by mahdiidea** [comment]
ممنون فقط من میتونم قبل از 
verify 
کردن مطمعن باشم که پرداخت موفق بوده ؟؟؟
نکنه من بیام مثلا یه بلیط رزرو کنم بعد مشکل 
verify
پیش بیاد و پول برگشت بخوره این وسط هیچ راهی برای ما نمیمونه

**Comment by mahdiidea** [comment]
بحث ارائه خدمات نیست من زمانی که دارم بلیط رو رزرو میکنم ممکنه چارتر به هر دلیلی بلیط صادر نکنه هرچند احتمال کمه ولی ما نمیخوایم مشتری برای پس گرفتن پولش مجبور به تماس باشه .
درگاهمون هم برای بانک ملته ، پیشنهاد شما برای این شرایط و این درگاه 
Verify 
کردن بعد از صدور بیلط هست !؟

**Comment by hamed-ehtesham** [comment]
این طور که میفرمایید  شما واسط هستید و در واقع نمیتونید به هر دو طرف اعتماد داشته باشید نه به درگاه نه به جایی که ازش بلیط میگیرید حالا باید یک طرف از این دو طرف شرایط رو برای برگشت عملیات فراهم کنند فکر من دو سال هست با درگاه ملت کار نکردم اما فکر میکنم با توجه به کدی که هست و البته دقیقش رو باید توی مستندات بانک بخونید بتونید اول تراکنش رو
verify
کنید بعد برید سراغ گرفتن بلیط اگر موفقیت آمیز بود تراکنش رو
settle
کنید و اگر نبود خطا برگردونید و
settle
نکنید و بانک ملت بعد از مدت زمانی که اون رو هم باید توی مستندات بانک بخونید پول رو برگشت خواهد داد

**Comment by mahdiidea** [comment]
ممنون دوست عزیز خیلی لطف کردی :)))
