### ISSUE TITLE
چرا مبالغ به صورت تومان ذخیره میشود ؟

### ISSUE THREAD

**Issue by vahidalvandi** [larabook/gateway#146]
من از سرویس 
sandbox
زیرین پال دارم استفاده میکنم اما قیمت هایی که در دیتابیس ذخیره میشه به صورت تومان است در صورتی که باید یکپارچگی در کل ماژول ها باشد که واحد همه را ریال در نظر بگیرد .

مثلا سبد خرید من 1 میلیون ریال است اما در دیتابیس 100 هزار میشودیعنی تقسیم بر 10 میکند .

از طرفی من میخواهم مبلغ سبد را با مبلغ ثبت شده مطابقت بدم نمی خونه

حالا این مشکل فقط برای زرین پال است یا ماژول ها مقدار
price
دیتابیس تومان ذخیره میشود ؟

**Comment by hamed-ehtesham** [comment]
اگه به یکپارچگی نیاز دارید میتونید از [مجموعه ی من](https://github.com/parsisolution/gateway) استفاده کنید

**Comment by vahidalvandi** [comment]
چرا این پکیجتون را روی همین نسخه که شناخته شده تر نمیارید؟

**Comment by hamed-ehtesham** [comment]
من اون رو از زیر نوشتم تفاوت های بنیادین داره با این مجموعه
و به نظر میرسه این مجموعه دیگه
maintenance
نداره مثال هاش همین تغییرات اخیر که روش انجام گرفته
و
issue
هایی که جواب داده نمیشن

**Comment by vahidalvandi** [comment]
ممنون از شما من هم مجموعه شما را تست میکنم و در صورتی که فرصت کنم در توسعه آن همکاری خواهم کرد

**Comment by hpakdaman** [comment]
> اگه به یکپارچگی نیاز دارید میتونید از [مجموعه ی من](https://github.com/parsisolution/gateway) استفاده کنید

سلام در صورت تکرار مجدد  متاسفانه مجبور میشم بلاکتون کنم . هر تغییری هست در همین پکیج اعلام کنید

**Comment by hamed-ehtesham** [comment]
سلام جناب پاکدامن
ضمن عرض خوشحالی بابت برگشتن شما به نگهداری این پکیج چیزی که من نوشتم به فراگیری پکیج شما نیست و تمامی درگاه هایی که شما پوشش میدهید را شامل نمیشود و مثل پکیج شما کاربری هم ندارد که درگاه های مختلف را به آن اضافه کنند و یا حتی آنها را تست کنند و مورد دیگر این که نسخه های لاراول را هم مانند شما پوشش نمیدهد الان تنها میتوان آن را روی لاراول 5.4 به بالا نصب کرد درحالی که شما حتی لاراول 4 را هم پشتیبانی میکنید بنابرین این که من تغییراتش را در اینجا اعمال کنم باعث به زحمت افتادن کاربران شما میشود و حتی بعضی دیگر نمیتوانند از آن استفاده کنند بنابرین نه شما این تغییرات را میپذیرید نه من همچین کاری میکنم
در این مدت که کمتر فرصت کردید به سوالات پاسخ دهید من سعی کردم به خاطر شناختی که نسبت به کد شما به سبب خواندن آن پیدا کرده بودم به سوالات در حد توان پاسخ دهم تا مشکلات دوستان حل شود اما این اواخر کمی کدها رو فراموش کرده بودم و شاید نتوانسته باشم به بهترین شکل دوستان رو راهنمایی کنم و حالا که خودتون برگشتید قطعا بهتر از بنده مشکلات رو رفع خواهید کرد
قطعا همین که شما بنده رو هم مثل اون دو فرد دیگری که بلاک کردید بلاک نکردید نشون میده که شما به خوبی متوجه تفاوت نیات بنده و آنها شده اید با این حال اگر جایی
comment
ی گذاشتم که باعث ناراحتی شما شده است پوزش میطلبم

با قدرت ادامه دهید 💪
شاد و پیروز باشید

**Comment by vahidalvandi** [comment]
@hpakdaman  با نظر آقای @hamed-ehtesham  موافقم
