### ISSUE TITLE
روش کار به کمک ajax

### ISSUE THREAD

**Issue by farshadfahimi1371** [larabook/gateway#147]
اگر بخوایم درخواست پرداخت رو به کمک ajax انجام بدیم 
و بعد از اون کاربر رو به صفحه پرداخت redirect کنیم 
متدی وجود داره که به ما مسیر پرداخت رو برگردونه یا خیر

**Comment by hamed-ehtesham** [comment]
با سلام
redirect
همیشه مسیر نیست بسته به درگاه گاهی باید با پارامتر های خاصی به یک جایی
post
صورت بگیره توسط 
form
بنابرین ......

**Comment by farshadfahimi1371** [comment]
من از طریق 
post با ajax 
درخواستم رو ثبت میکنم و درخواست پرداخت رو هم ارسال میکنم 
بعد از اون باید کاربر رو به درگاه ارسال کنم برای همین امکانش نیست که از متن 
redirect 
استفاده کنم
برای همین میخوام 
url
پرداخت رو داشته باشم که بعدا با 
javascript کاربر رو 
redirect 
کنم

**Comment by hamed-ehtesham** [comment]
متوجه هستم
فکر کنم منظور من رو متوجه نشدید
برای فرستادن کاربر به درگاه همیشه یک شکل وجود نداره برای هر درگاه متفاوت هست
همیشه یک
url
نیست که به اون
redirect
کنید گرچه بعضی از درگاه ها این شکلی هست

**Comment by hamed-ehtesham** [comment]
برای بعضی از درگاه ها باید پارامتر های خاصی رو به آدرس درگاه
post
کنید

**Comment by farshadfahimi1371** [comment]
جواب رو پیدا کردم برای اینکار باید از روش زیر استفاده کنیم 

$gateway->redirect()->getTargetUrl()

این خط کد مسیری که باید 
redirect 
بشه رو به ما برمیگردونه

**Comment by hamed-ehtesham** [comment]
بله درست هست اما حواستون باشه که این کد برای همه ی درگاه ها با توجه به توضیحاتی که دادم کار نمیکنه
