### ISSUE TITLE
class gateway does not exists

### ISSUE THREAD

**Issue by greatamir** [larabook/gateway#15]
من به هر روشی که میخوام آبجکت بسازم 
مثلا اینطوری
         $gateway = Gateway::make(new Larabookir\Gateway\Mellat\Mellat());
این ارورو میده
Class gateway does not exist

**Comment by hpakdaman** [comment]
شما سرویس پروایدرش رو آیا در فایل 
app
رجیستر کردید ؟ 
اگر از فاساد میخواید استفاده کنید به این شکل کد بزنید 
$gateway = \Gateway::make(new Larabookir\Gateway\Mellat\Mellat());

 این اسلش خیلی ارور رایجی هست و به خاطر تداخل نیم اسپیس ها هست .

**Comment by mohamamd-chavoshipor** [comment]
سلام خسته نباشید
من نصب رو انجام دادم مشکلی هم نیست
میخام به زرین پال اتصال برقرار کنم از کد زیر استفاده کردم:
`$gateway = Gateway::make(new Larabookir\Gateway\Zarinpal\Zarinpal());`
بعد با این ارور رو به رو میشم:
`Class 'App\Http\Controllers\Gateway' not found`
مشکل کجاست؟
ممنون

**Comment by mohamamd-chavoshipor** [comment]
تو کامنت ها این یکی این مشکل و داشته Facad رو هم انجام دادم کلا از اول کار رو بدون ارور انجام دادم مشکلی نبوده 
ولی تو برقرار ارتباط مشکل هستش

**Comment by hshmghfard** [comment]
با سلام
خسته نباشید
ببخشید من از پکیج تون خواستم استفاده کنم از بخش زرین پال که با خطای "کد مرچنت یا ای پی اشتباه می باشد " برخورد می کنم در حالی که کد رو چک کردم درست بود و ای پی هم اصلا محدودیتی روش نزاشتم و بدون محدودیت هستش
می خواستم ببینم مشکل من چیه؟

**Comment by hpakdaman** [comment]
روی وبسایت لوکال تست میکنید  ؟

**Comment by ilbeygi** [comment]
سلام
بنده روی لوکال تست میکنم همین ارور رو میده

**Comment by hpakdaman** [comment]
سلام 
پشت نام تمامی کلاس هاتون
 "/ "
قرار دهید مثل : 
\Gateway::make
موفق و پیروز باشید

**Comment by saber13812002** [comment]
Class 'Mellat' not found

هر کاری میکنم اینو نمیشناسه

            $gateway = \Gateway::make(new \Mellat());


به این خط گیر میده

نمیدونم کامپوننت دیگه نصب هم ندارم که کانفلینک کرده باشه

لاراول اخرین نسخه هستش

پشت همه ی کلاس هامم بک اسلش هستش

حدس میزنم احتمال بالا باشه که با نیم اسپس تداخل کرده باشه ولی من چیزی به نام ملت ندارم

**Comment by saber13812002** [comment]
finally i set

            $gateway = \Gateway::mellat();


and it worked
