### ISSUE TITLE
کار نکردن publish 

### ISSUE THREAD

**Issue by jzcs89** [larabook/gateway#150]
وقت بخیر
پابلیش میزنم هیچی برام اضافه نمیشه
یه دستور دیگه هم دوستان گفته بودن تو توضیحات قبلی زدم بازم نشد
به صورت دستی اضافه کردم به جز مایگریشین ها و پوشه کانفیگ چیز دیگه ای هم میخواد اضافه کنم؟

**Comment by hamed-ehtesham** [comment]
سلام و وقت بخیر
اگر از درگاه های
psp
استفاده میکنید و نیاز به شخصی سازی صفحه ی انتقال دارید محتویات (فایلهای) داخل پوشه ی
`views`
رو هم انتقال بدید به این آدرس
`resources/views/vendor/gateway/*.blade.php`
در غیر این صورت نیاز نیست

**Comment by jzcs89** [comment]
> سلام و وقت بخیر
> اگر از درگاه های
> psp
> استفاده میکنید و نیاز به شخصی سازی صفحه ی انتقال دارید محتویات (فایلهای) داخل پوشه ی
> `views`
> رو هم انتقال بدید به این آدرس
> `resources/views/vendor/gateway/*.blade.php`
> در غیر این صورت نیاز نیست

دست شما درد نکنه

**Comment by MohebGh** [comment]
سلام بنده هم همین مشکل دارم
پابلیش کار نمیکنه هر کاری کردم نشد ورژن لاراول من 5.6 هستش..چکار کنم

ممنون
