### ISSUE TITLE
خطا در استفاده از فانکشن ready

### ISSUE THREAD

**Issue by F4rzane** [larabook/gateway#158]
بعد از این خط  $gateway->price(1000)->ready(); من خطای زیر رو میگیرم
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where `id` = ? limit 1' at line 1 (SQL: select * where `id` = 154867827354 limit 1)

**Comment by hamed-ehtesham** [comment]
احتمالا کد شما به فایل
config
دسترسی نداره

**Comment by F4rzane** [comment]
چجوری میتونم حلش کنم؟

**Comment by hamed-ehtesham** [comment]
اگر مراحل گفته شده برای نصب رو انجام داده باشید نباید به مشکل بر بخورید
اگر نیاز به کمک بیشتری دارید باید توضیحات بیشتری از نحوه ی استفاده تون بدید

**Comment by saber13812002** [comment]
@F4rzane please mention your version here.

version of laravel and your custom configurations

**Comment by AhmadPayamani** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where `id` = ? limit 1' at line 1 (SQL: select * where `id` = 156544092630 limit 1)

منم همین خطا رو دارم
laravel 5.8

**Comment by snowman15** [comment]
و منم
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'where `id` = ? limit 1' at line 1 (SQL: select * where `id` = 156697988197 limit 1)

**Comment by hpakdaman** [comment]
check here : https://github.com/larabook/gateway/issues/192#issuecomment-549075173
