### ISSUE TITLE
مشکل در نصب پکیج

### ISSUE THREAD

**Issue by hadiaec20h** [larabook/gateway#159]
با سلام.
من بعد از نصب در لاراول 5.7 و انجام مراحل ذکر شده نتوانستم فایل
 gateway.php
را در پوشه کانفیگ بیابم
بعد از اجرای دستور زیر نیز چیزی برای مایگریت وجود نداشت
php artisan migrate

**Comment by saber13812002** [comment]
php artisan migrate

فایل های مربوط به ساختن جداول رو اجرا میکنه

اگر چیزی نداشته باشید خب اتفاقی نمیافته

اما بدونید که شما نیاز دارید که اطلاعات قبل از ارجاع کاربر به بانک رو یک جایی ذخیره کنید که وقتی برگشت بدونید چه کاربری بوده که براش پرداخت رو ثبت کنید

یا نتیجه رو برایش پیامک کنید.

یا محصول درخواستی اش رو براش ثبت نهایی آماده برای ارسال کنید

پی نیاز به یک جدول دارید که خودتون هر جور بخواهید میتونید طراحیش کنید

تازه اگر من جای مستند ساز تیم بودم مینوشتم

اگر مایگریت دارید

دستور زیر رو یکش رو بسته به نیاز تون اجرا کنید
php artisan migrate
or
php artisan migrate:reset
or
php artisan migrate:refresh
or
nothing
