### ISSUE TITLE
خطا در اتصال به درگاه بانک ملت

### ISSUE THREAD

**Issue by abbasi-hadi** [larabook/gateway#161]
سلام وقت بخیر ما چند مدتی هست که هنگام اتصال به درگاه بانکی با خطای زیر مواجه میشیم خواهش میکنم بررسی کنین که چرا این خطا ایجاد میشه 
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl' : failed to load external entity "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"
خواهش میکنم هرچه زودتر ی راهنمایی کنین مرسی

**Comment by saber13812002** [comment]
i have this error 

any solution?

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl' : failed to load external entity "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"

**Comment by saber13812002** [comment]
این خطوط رو جایگزین کنید در فایل 
mellat.php

مشکل حل میشه

		try {
			$context = stream_context_create(
				[
					'ssl' => array(
						'verify_peer'       => false,
						'verify_peer_name'  => false
					)
				]
			);

			$soap = new SoapClient($this->serverUrl,  [
				'stream_context' => $context
			]);

			//$soap = new \SoapClient($this->serverUrl);
