### ISSUE TITLE
Using with Lumen

### ISSUE THREAD

**Issue by hamraa** [larabook/gateway#185]
Error:

In GatewayServiceProvider.php line 56:
Class 'Illuminate\Foundation\Application' not found

I set lumen bootstrap settings correctly.

**Comment by hamraa** [comment]
any help?!!

**Comment by hamraa** [comment]
no idea ?!

**Comment by khanzadimahdi** [comment]
use below package for laravel and lumen

https://github.com/shetabit/payment

**Comment by hamraa** [comment]
@khanzadimahdi Tnx. I'll try it.

**Comment by hamraa** [comment]
I finally wrote a package based on larabook package:

https://github.com/hamraa/lumen-payment

**Comment by khanzadimahdi** [comment]
i will be happy if you develope below package for lumen

https://github.com/shetabit/payment
