### ISSUE TITLE
خطا در بازگشت از بانک پارسیان

### ISSUE THREAD

**Issue by ehsannowrouzi** [larabook/gateway#186]
بعد از پرداخت موفق از طریق درگاه بانک پارسیان ، gateway->verify انجام نمیشه ، و خطای درخواست غیر معتبر دریافت می کنم چون status برابر با 0 هست ، کسی می تونه کمک کنه ؟

**Comment by ehsannowrouzi** [comment]
مشکل با کد دوست عزیزمون حل شد ، از اینجا ببینید:
https://github.com/larabook/gateway/issues/123#issuecomment-404049675

**Comment by psobhanlo** [comment]
چرا این رو تو خود پکیج درست نمیکنید؟؟؟؟

بعد کلی کلنجار فهمیدم که بانک پارسیان  
status 0
رو تو برگشت درگاه تایید شده میدونه

**Comment by hamed-ehtesham** [comment]
فکر میکنم مشکل [اینجا](https://github.com/parsisolution/gateway) حل شده باشه

**Comment by Raymonsystem** [comment]
سلام
منم این مشکلو داشتم و حل شد
حالا بعد از برگشت از بانک یک ارور دارم:
UNDEFINED INDEX: IDINVOICE

این چیه؟ باید چیکار کنم؟

**Comment by hpakdaman** [comment]
issue fixed here : [https://github.com/larabook/gateway/pull/196](url)
