### ISSUE TITLE
Class 'Illuminate\Support\Facades\Input' not found in laravel 6

### ISSUE THREAD

**Issue by mohammad-salehnia** [larabook/gateway#198]
Symfony\Component\Debug\Exception\FatalThrowableError
Class 'Illuminate\Support\Facades\Input' not found
----
Larabookir\Gateway\Zarinpal\Zarinpal::userPayment
:210
C:\X\X\vendor\larabook\gateway\src\Zarinpal\Zarinpal.php
----
protected function userPayment()

	{

		$this->authority = Input::get('Authority');

		$status = Input::get('Status');

		if ($status == 'OK') {

			return true;

		}

		$this->transactionFailed();

		$this->newLog(-22, ZarinpalException::$errors[-22]);

		throw new ZarinpalException(-22);

	}

**Comment by hamed-ehtesham** [comment]
this package doesn't work with Laravel 6 yet
you can get help from #197 or use [this other package](https://github.com/parsisolution/gateway)

**Comment by khanzadimahdi** [comment]
use below package instead

https://github.com/shetabit/payment

**Comment by hpakdaman** [comment]
supports laravel 6 since now ! update the new version .
