### ISSUE TITLE
"Could not connect to host" error

### ISSUE THREAD

**Issue by Anisi** [larabook/gateway#26]
Hello
When I want to connect to "mellat gateway", after a delay, almost always the error "Could not connect to host" occurs.
I googled it and I couldn't find a proper solution, but i realized that it is related to soap library.
What should I do?
Thanks

**Comment by hpakdaman** [comment]
hello Mojtaba,
this error may related to several things.
maybe  your IP is blocked in bank mellate side . some  hosting server
provider they are blocked by Bank Mellat. also you can't connect to bank
from local computer.

**Comment by Anisi** [comment]
Thanks for your response
Maybe it's bank's problem, because I am developing and sending many requests; but I thinks it isn't blocked me, because often this error happens not always!
I contacted my hosting provider and they believe that the problem is not caused by them.
About connecting from local PC, I know about that and it isn't allowed for transaction because of filtering IP at bank side.

**Comment by Anisi** [comment]
Hello
Thanks for your attention.
I apprised Mellat support agent and they confessed that the problem is on their side. The problem is fixed now.
