### ISSUE TITLE
مشکل در هنگام استفاده با soap

### ISSUE THREAD

**Issue by saeed7m** [larabook/gateway#32]
سلام و تشکر از پکیج پر کاربردتون
بعد از نصب موفق در هنگتم اجرا با خطای زیر مواجه می شم که ظاهرا باید از nusoap استفاده کنم 
لطفا راهنمایی بفرمایید 

FatalErrorException in Mellat.php line 23: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl' : failed to load external entity "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"

**Comment by saber13812002** [comment]
این خطوط رو جایگزین کنید در فایل 
mellat.php

مشکل حل میشه

		try {
			$context = stream_context_create(
				[
					'ssl' => array(
						'verify_peer'       => false,
						'verify_peer_name'  => false
					)
				]
			);

			$soap = new SoapClient($this->serverUrl,  [
				'stream_context' => $context
			]);

			//$soap = new \SoapClient($this->serverUrl);
