### ISSUE TITLE
Callback redirection results localhost port 80

### ISSUE THREAD

**Issue by koorosh13hm** [larabook/gateway#35]
سلام ،
آیا امکان استفاده از این افزونه تحت شرایط لوکال هاست هم وجود دارد؟ اگر بله مقادیر فایلهای کانفیگ باید چه باشد؟ آدرس بار بنده فقط مقدار رو به رو را برگشت میدهد :
http://localhost/PaymentSuccessfulController?transaction_id=1478690760&_token=xzr6KVQ5NJWjLNtvxAKS44Jad3ciOQwN5KeEHiIL&Authority=000000000000000000000000000027760208&Status=OK
برای اینکه درست کار کند باید به پورت ۸۰۰۰ رجعت کند که نمیکند.
فکر میکنم تنظیمات درست باشد. لطفا من را راهنمایی کنید.
ممنونم.

**Comment by hpakdaman** [comment]
سلام . بله امکانش هست من خودم در حال حاضر روی لوکال هاستم کار میکنم. البته
فکر کنم باید virtual host بسازید که تو اینترنت روش ساختنش رو میتونید پیدا
کنید خودم هم یه ویدیو آموزشی توی سایتم گذاشتم که روش نصب لاراول رو رو
virtual host توضیح دادم. پاینده باشید

**Comment by koorosh13hm** [comment]
آقای عزیز
ممنون از پاسخ شما. به محض اینکه بتوانم آنرا بررسی کرده و نتیجه را همینجا به اطلاع شما میرسانم.
با تشکر مجدد.

**Comment by koorosh13hm** [comment]
از طریق زیر یک ویرتوالل ساختم و اکنون دارد درست کار میکند (سیستم عامل من لینوکس است). خیلی از شما ممنونم:
https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/
فقط یک سوال دیگر دارم : ای کاش میدانستم دلیل اینکه حتما باید از پورتِ ۸۰ استفاده کرد چیست ؟ آیا راهی وجود دارد که برگشت (کال بک) به پورت مورد نظر من انجام شود؟
صمیمانه سپاسگذارم.

**Comment by hpakdaman** [comment]
سلام . من یادم نمیاد جایی ذکر کرده باشم که حتما باید از پورت 80 استفاده
کنید . تو تنظیمات ویرچوال همونجا میشه پورت دو معرفی کرد و نیاز نیست تو url
وارد کنید
