### ISSUE TITLE
in laravel 5.3 refId() not work

### ISSUE THREAD

**Issue by arman666a** [larabook/gateway#37]
در لاراول 5.2 تست کردم و خطایی وجود نداشت همه چیز خوب بود.
حالا با لاراول 5.3 که اومدم وصل بشم به درگاه های مختلف دیدم خطای دیتابیس میده که رفرنس آیدی نمیتونه مقدار خالی داشته باشه.
رفتم تنظیمات دیتابیس و جدول ترنزکشن رو دیدم و فیلد رفرنس آیدی رو گذاشتم بتونه خالی بره جلو.
الان داره کار میکنه و وقتی میریم به درگاه بانک رفرنس آیدی در جدول ترنزکشن مقدار رو میگیره
حالا مشکل کجاست که در لاراول 5.2 خوب کار میکرد الان نه؟

**Comment by arman666a** [comment]
البته با استفاده از 
nullable
مشکل حل میشه

**Comment by hpakdaman** [comment]
بله . میتونید nullable کنید تا مشکل حل شه . همچنین توی نسحخ جدید مشکل رو حل
کردیم

**Comment by arman666a** [comment]
متاسفانه اخیرا زرینپال خدمات زرین گیت رو نمیتونه ارائه بده.
بهتر نیست یک شرکت واسط دیگه ای رو که ارائه میده این خدمات رو اضافه کنید؟

**Comment by ilbeygi** [comment]
با سلام و خسته نباشید
بنده از زرین پال استفاده میکنم ، مشکل وصل شدنم به درگاه برطرف شد ولی یکی مشکل دیگه پیدا کردم.
ممنون میشم اگر کمک کنید و بگید ک باید چ کرد.

بسیار سپاس
![2016-11-25_120119](https://cloud.githubusercontent.com/assets/23147213/20619004/49b446dc-b307-11e6-992c-24e546d514e0.png)

**Comment by hpakdaman** [comment]
آقای ایل بیگی ،
اگر میخواید با این سبک صدا بزنیداز نام درگاه را به حروف کوچیک صدا بزنید . مثلا : 
Gateway::mellat()
Gateway::zarinpal()
...

**Comment by hpakdaman** [comment]
> متاسفانه اخیرا زرینپال خدمات زرین گیت رو نمیتونه ارائه بده.
بهتر نیست یک شرکت واسط دیگه ای رو که ارائه میده این خدمات رو اضافه کنید؟

من که تست کردم اوکی بود .

**Comment by arman666a** [comment]
بله من تست کردم، دوباره زرین گیت رو فعال کردن
