### ISSUE TITLE
خطا در درگاه بانک پاسارگاد

### ISSUE THREAD

**Issue by Ahmad110** [larabook/gateway#38]
سلام
اطلاعات ارسالی برای کال بک در وب سرویس درگاه پاسارگاد نباید شامل علامت سئوال باشه در صوتی که شما همراه کال بک توکن سی اس آر اف و شناسه تراکنش رو هم فرستادید . اینا باعث میشن فروشگاه توسط وب سرویس قابل شناسایی نباشه و خطا ایجاد بشه .

**Comment by Ahmad110** [comment]
مشکل از فانکشن گت کال بک در فایل پاسارگاد بود و باید بصورت زیر ویرایش بشه :+1: 
```
	function getCallback()
	{
		if (!$this->callbackUrl)
			$this->callbackUrl = $this->config->get('gateway.pasargad.callback-url');

		return $this->callbackUrl;
	}
```

**Comment by hpakdaman** [comment]
احمد جان سی آر اف اگر ارسال نشه در صورتی که روتر از نوع 
POST
تعریف شده باشه لاراول خطا خواهد داد. 
ولی اگر این بانک پاسارگاد کو
