### ISSUE TITLE
Sample files

### ISSUE THREAD

**Issue by erfansahaf** [larabook/gateway#42]
Please add sample code (with Routes) for each Bank to new `sample` directory of the repository.
Thanks.

**Comment by hpakdaman** [comment]
http://larabook.ir/%D8%A7%D8%AA%D8%B5%D8%A7%D9%84-%D8%AF%D8%B1%DA%AF%D8%A7%D9%87-%D8%A8%D8%A7%D9%86%DA%A9-%D9%84%D8%A7%D8%B1%D8%A7%D9%88%D9%84/
