### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by ebrahimirad** [larabook/gateway#43]
Hi

I want to run the example for Mellat gateway, but I get below error:
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl' : failed to load external entity "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"

Please help me
Thanks

**Comment by kamrava** [comment]
Do you have php-soap installed?

**Comment by Anisi** [comment]
I had same issue before. Usually it's caused by problems of mellat's sever.

**Comment by cracki** [comment]
Local SSL Error. add:
```
"stream_context" => stream_context_create(
                    [
                        'ssl' => array(
                            'verify_peer'       => false,
                            'verify_peer_name'  => false,
                        )
                    ]
                )
```

**Comment by PedramK** [comment]
Much appreciated @cracki 
`SoapClient` takes a stream context in its parameters, which you can create yourself.
```php
$context = stream_context_create(
  [
     'ssl' => array(
       'verify_peer'       => false,
       'verify_peer_name'  => false
    )
  ]
);
```
So add this options as second argument when you're creating SoapClient object:
```php
$soap = new SoapClient($this->serverUrl,  [
  'stream_context' => $context
]);
```

**Comment by amircb1367** [comment]
i have this error too but dont solve with add $context as second argument

**Comment by saber13812002** [comment]
i had this error so i can solve it by adding context as seconf argument thanks @pedramk
