### ISSUE TITLE
خطا تایید پرداخت در بانک پاسارگاد

### ISSUE THREAD

**Issue by raftx24** [larabook/gateway#44]
سلام
تشکر بابت کتابخونه جامعتون
بانک پاسارگاد در وریفای دو مرحله تایید نیاز داره و در حال حاضر به وضعیت ؛موفق - در انتظار تایید؛ می رسه ولی تایید نهایی انجام نمیشه در نتیجه بعد از مدتی خرید ناموفق می شه

**Comment by Ahmad110** [comment]
سلام
شما بعد از تراکنش رفرنس آی دی میگیری ؟ یعنی تو دیتابیس ثبت میشه ؟

**Comment by raftx24** [comment]
من بررسی کردم دیدم که شما یه چیزی رو فراموش کردین که اضافه کنین اون هم ولید کردن پرداخت هست در غیر این صورت پول به حساب کسی که خرید کرده بر میگرده در واقع ولیدیشن شما از طریق اطلاعات تو دیبتابیس و چک کردن با بانک بود.
انتهای تابع وریفای من این رو اضافه کردم که از خوده کد پاسارگاد هم هست
` $fields = array(
            'MerchantCode' => $array["merchantCode"],
            'TerminalCode' => $array["terminalCode"],
            'InvoiceNumber' => $array["invoiceNumber"],
            'InvoiceDate' => $array["invoiceDate"],
            'amount' => $array["amount"],
            'TimeStamp' => date("Y/m/d H:i:s"),
            'sign' => ''
        );

        $processor = new RSAProcessor($this->config->get('gateway.pasargad.certificate-path'), RSAKeyType::XMLFile);
        $data = "#" . $fields['MerchantCode'] . "#" . $fields['TerminalCode'] . "#" . $fields['InvoiceNumber'] . "#" . $fields['InvoiceDate'] . "#" . $fields['amount'] . "#" . $fields['TimeStamp'] . "#";
        $data = sha1($data, true);
        $data = $processor->sign($data);
        $fields['sign'] = base64_encode($data); // base64_encode
        $verifyresult = Parser::post2https($fields, 'https://pep.shaparak.ir/VerifyPayment.aspx');
        $array = Parser::makeXMLTree($verifyresult);
        $array = $array["actionResult"];
        if ($array["result"] != "True")
            throw new PasargadErrorException(Enum::TRANSACTION_FAILED_TEXT);


        $this->newLog($array['result'], Enum::TRANSACTION_SUCCEED_TEXT);
   `

**Comment by Ahmad110** [comment]
بله اما این کتابخانه بر اساس سیستم تک مرحله ای بانک پاسارگاد نوشته شده . شما بعد از تراکنش رفرنس آی دی میگیرید ؟ اگه بله امکانش هست که اونو بهم بدید که ببینم بانک بهتون چی برمیگردونه ؟

**Comment by raftx24** [comment]
بله می گیرم 
636234*********844781

**Comment by Ahmad110** [comment]
خب ظاهرا خودتون تایید مرحله دوم رو اضافه کردید . بهتره که با کد جدیدتون یک پول رکوئست ایجاد کنید تا آقای پاکدامنه کد رو آپدیت کنه .

**Comment by hpakdaman** [comment]
من منتظر هستم تا پول رکوئست رو بفرستید . اگر ممکنه سریعتر انجامش بدید چون کاربرای زیادی بهش احتیاج دارن با تشکر

**Comment by Ahmad110** [comment]
سلام
متاسفانه مرچنت من تک مرحله ای هستش اما من کد تایید مرحله دوم رو نوشتم . فقط کافیه این دوستمون چک کنه و در صورت تایید کدها آپدیت بشه .
لینک کد :
[Pasargad.zip](https://github.com/larabook/gateway/files/800979/Pasargad.zip)

http://pastebin.com/WYED60rS

**Comment by AGhasemzadeh** [comment]
سلام
من از درگاه پاسارگاد استفاده می کنم الان این آپدیت اعمال شده است؟ چون خیلی مهمه.

**Comment by salmanta** [comment]
> 
> 1
> --
> لینک کد :Pasargad.ziphttp://pastebin.com/WYED60rS
> 

این کد به مشکل میخوره توی پارس کردن.
من امروز پول ریکوئست میفرستم

**Comment by erfansahaf** [comment]
برای کسایی که تایید دو مرحله تراکنش رو ایجاد نکردن مشکلی پیش نمیاد؟

**Comment by salmanta** [comment]
نه من تنظیمات گذاشتم که بگید تک مرحله ای هست یا دو مرحله ای
ولی هنوز PR نزدم
اولین فرصت این کار رو انجام میدم

**Comment by mmehdibalouchi** [comment]
این مشکل هنوز برطرف نشده ؟
با این اررور رو به رو می شه
این ارور پیش می آید
Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION)

Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION)
--
in Pasargad.php (line 165)
یک کروشه بسته نشده

**Comment by vahidalvandi** [comment]
متاسفانه کد تست نشده روی سورس آپدیت شده .
لطفا کد را تست کنید چون در حال حاضر مشکل داره

**Comment by hpakdaman** [comment]
با سلام . کد ها بروز شدن لطفا مجددن تست کنید و اعلام بفرمایید\
با تشکر

**Comment by vahidalvandi** [comment]
من در این برنچ این مشکل را نیز حل کرده بودم
https://github.com/vahidalvandi/gateway

اگر پاسارگاد هنوز مشکل داره میتونید یه نگاهی به پاسارگاد این هم بندازید

**Comment by hpakdaman** [comment]
باید منتظر بمونیم دوستانی که پاسارگاد دارند بیان تست کنند
