### ISSUE TITLE
برگشت از بانک

### ISSUE THREAD

**Issue by abbasamini** [larabook/gateway#47]
سلام من پس از برگشت از بانک می خوام اگر خطایی رخ داد کاربر رو به یک View خاص بفرستم ولی امکان نداره و فقط خطای پکیجGateway داده میشه

**Comment by hpakdaman** [comment]
سلام . فقط کافیه توی اکسپشن خطا رو به ویو پاس بدید

try{
    ...
}catch(\Exception $e){
    return view('...')->withErrors($e->getMessage());
}
