### ISSUE TITLE
"چنین رکورد پرداختی موجود نمی باشد." Error

### ISSUE THREAD

**Issue by Anisi** [larabook/gateway#48]
Hello
After calling the callback URL, always this error happens even though the record exists.

**Comment by hpakdaman** [comment]
salam .  shoma packageton ro update kardid in masalee be vojod omad ? 

aya bad az update migrate karde bodid ?

**Comment by Anisi** [comment]
سلام
بله با آپدیت این اتفاق افتاد.
دیتابیس رو هم درست کردم. فقط یک فیلد افزایش اندازه داشته
جالب اینه در لوکال مشکلی ندارم اما روی سرور این خطا نمایش داده می‌شه
رو حذف کردم همه رکوردها موجود هستند از جمله همون تراکنش. ID کویری رو هم تغییر دادم وقتی شرط جستجو روی

**Comment by hpakdaman** [comment]
تو آنلاین دیتابیس چک کنید دوتا فیلد هست
transactions.id   , transactions_log.transaction_id

این دوتا فیلد باید از نوع 
bigint 
باشند . 
درحقیقت پکیج مشکلی نداره  . ما این فیلد رو توی آپدیت جدیدمون طولش رو تغییر دادیم ولی نمیدونم چرا مایگریشنش برای بعضی از یوزر ها کا نکرده

**Comment by Anisi** [comment]
bale migration baraye bande ham kar nakard va dasti tagheerate lazem ro emal kardam.
babate do field dorost hastan, moshkel faghat dar query hast vagarna transaction dar db insert shode.

**Comment by hpakdaman** [comment]
transaction dar db insert mishe ama  bejaye inke ID biginteger insert beshe dare integer zakhirash mikone ke eshtebahe . 

moshkeleton hamon bigint hast ke emal nashode bayad in moshkel ro hal konid

**Comment by Anisi** [comment]
Kheir, emal shode va check ham kardam toole adade insert shode 13 hast.

**Comment by hpakdaman** [comment]
bizahmat be man tamas begirid ta mostaghim teamviewer bezanam moshkeleton ro hal konam.  09177879986

**Comment by ranahaarb** [comment]
این مشکل برای منم پیش اومده

**Comment by htaghizadeh** [comment]
این مشکل برای من هم پیش اومده، توی متد verify هم intval رو حذف کردم توی این تکه کد مشکل رفع شد!

**Comment by Anisi** [comment]
@htaghizadeh vaghan mamnoon! moshkele manam ba hamin rahkar hal shod.

**Comment by hpakdaman** [comment]
سلام. تغییراتی اعمال کردم. احتمالا مشکل حل شده باشه. آبدیت کنید تست کنید
خبرم بدید

**Comment by Anisi** [comment]
mamnoon babate pqygiritoon
moshkel hal shod
