### ISSUE TITLE
نتیجه تراکنش قبلا از طرف بانک اعلام گردیده

### ISSUE THREAD

**Issue by sjys** [larabook/gateway#51]
این اکسپشن تو چه حالتهایی رخ میده؟من چندتا فرم پرداخت دارم که همه به یه فانکشن برمیگردن ولی فقط یه فرم این اکسپشن رو میده
تو این خط $gateway = \Gateway::verify();

**Comment by hpakdaman** [comment]
این زمانی رخ میده که شما دوبار عملیات وریفای رو کال کنی
