### ISSUE TITLE
خطای هنگتم اتصال به درگاه پارسبان

### ISSUE THREAD

**Issue by vahidalvandi** [larabook/gateway#54]
در هنگام اتصال به درگاه خطای زیر را میدهد

Server was unable to read request. ---> There is an error in XML document (2, 257). ---> Value was either too large or too small for an Int32.

**Comment by vahidalvandi** [comment]
دلیل این خطا در مقدار 
orderid
میباشد مقداری 12 رقمی uid
را بانک پارسیان نمیتواند دریافت کند

**Comment by salmanta** [comment]
#57
