### ISSUE TITLE
Class gateway does not exist

### ISSUE THREAD

**Issue by alisaghari** [larabook/gateway#56]
بعد از قرار دادن این کد ها در بخش web.php
با این خطا برخوردم :
Class gateway does not exist
لطفا این باگ وجود دراه یا مشکلی دیگری هست ؟
Route::get('req',function(){
    try {

        $gateway = Larabookir\Gateway\Gateway::mellat();
        $gateway->setCallback(url('callback/from/bank'));
        $gateway->price(1000)->ready();
        $refId =  $gateway->refId();
        $transID = $gateway->transactionId();

        // Your code here

        return $gateway->redirect();

    } catch (Exception $e) {

        echo $e->getMessage();
    }
});

Route::any('callback/from/bank',function(){
    try {

        $gateway = \Gateway::verify();
        $trackingCode = $gateway->trackingCode();
        $refId = $gateway->refId();
        $cardNumber = $gateway->cardNumber();

        // عملیات خرید با موفقیت انجام شده است
        // در اینجا کالا درخواستی را به کاربر ارائه میکنم

    } catch (Exception $e) {

        echo $e->getMessage();
    }
});

**Comment by hpakdaman** [comment]
سلام . خیر باگ وجود نداره . 
احتمالا فاساد رو به 
config/app.php
اضافه نکردید .

**Comment by akoSalman** [comment]
```php artisan cache:clear
php artisan config:cache
```
