### ISSUE TITLE
نبود فیلد additional data

### ISSUE THREAD

**Issue by AGhasemzadeh** [larabook/gateway#59]
سلام
با تشکر از درست کردن این بسته
اما متاسفانه یک مشکلی که این بسته دارد این هست که زمان ارسال اطلاعات به بانک نمیشود اطلاعات اضافه را به بانک ارسال کرد
که خیلی مهم هست.

**Comment by erfansahaf** [comment]
سلام

کدوم درگاه مد نظرتون هست؟ قبلا این امکان برای درگاه زرین پال اضافه شده، لطفا مستندات درگاه مورد نظرتون رو قرار بدید بررسی شه اگر امکانش وجود داشت آپدیت کنیم

**Comment by MohammadMghsoudi** [comment]
من هم این مشکل رو دارم و از درگاه سامان استفاده می کنم
لینک مستند درگاه بانک سامان:
https://www.sep.ir/Data/Sites/1/media/epay/2.SEP-PPG-Purchase%20With%20Mobile%20Number-TechnicalSpecification.pdf

**Comment by hamed-ehtesham** [comment]
برای ارسال اطلاعات اضافه و ذخیره شدن به صورت خودکار این اطلاعات درون پایگاه داده میتونید از [این مجموعه](https://github.com/parsisolution/gateway) استفاده کنید
