### ISSUE TITLE
Adding Iran Kish payment

### ISSUE THREAD

**Issue by AGhasemzadeh** [larabook/gateway#63]
سلام
وقت بخیر
ممنون از این که این پکیج را درست کردید

من می تونم خودم درگاه ایران کیش را اضافه کنم اما نمی دونم چطوری توی گیت کاری کنم که به این بسته اضافه شود
اگر توضیح بدهید ممنون می شوم

خیلی ممنون
[Token.pdf](https://github.com/larabook/gateway/files/1117290/Token.pdf)

**Comment by hpakdaman** [comment]
با سلام . 
بسیار ساده است . 
کافیه توی این صفه 
https://github.com/larabook/gateway
گزینه 
Upload Files 
رو بزنی و فایل هاتو به صورت دسته ای آپلود کنی .

**Comment by AGhasemzadeh** [comment]
آپلود بسته هست

**Comment by hpakdaman** [comment]
روش دیگه اینه اول پروژه رو 
fork 
کنید تا یه انشعاب برای شما ایجاد بشه 
سپس میتونید تغیرات را روی انشعاب خودتون ایجاد کنید
در نهایت برای اینکه تغییرات برای ما ارسال بشه باید درخواست 
merge
بزنید

اینم جهت راهنمایی :
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

برای فورک کردن هم باید اول عضو شین و توی گیت هاب لاگین کنید و به آدرس پروژه ما بیاید سپس دکمه فورک نمایان خواهد شد

**Comment by vahidalvandi** [comment]
سلام این ایران کیش الان خیلی طرفدار داره . حتی بیشتر از مواردی که درحال حاضر وجود داره . اما چطوری باید یک مورد جدید را اضافه کنیم ؟

یا اینکه آیا خودتون ایران کیش را اضافه میکنید ؟

**Comment by AGhasemzadeh** [comment]
سلام
shirazsoft/gateway
ایران کیش را هم دارد
