### ISSUE TITLE
بروز نگه داشتن fork

### ISSUE THREAD

**Issue by AGhasemzadeh** [larabook/gateway#67]
سلام
وقت بخیر
من یک سوال داشتم
من یک
fork 
از ریپازیتوری شما برای خودم ایجاد کردم حالا چطوری می تونم کاری کنم که همیشه بروز باشه و کد های شما داخل اون باشه ؟ اصلا شدنی هست؟

**Comment by hpakdaman** [comment]
با سلام . بله فقط کافیه از ریپازیتوری ما به ریپازیتوری خودتون مرج بکنید .
موفق باشید

**Comment by AGhasemzadeh** [comment]
سلام
میشه توضیح بیشتری بدهید

**Comment by hpakdaman** [comment]
الان توی فورکی که برای خودتون ایجاد کردید یک گزینه با نام
Create Pull Request
باید بتونید پیدا کنید
اون رو بزنید و برنچ ما و خودتون رو انتخاب کنید تا تغییرات براتون بیاد سپس گزینه 
merge 
رو بزنید .

یکمی تو اینترنت مطالعه کنید مستندات زیاده
