### ISSUE TITLE
متد makeCallback و urlModify

### ISSUE THREAD

**Issue by erfansahaf** [larabook/gateway#71]
درحال نوشتن درگاه جدید برای پکیج هستم اما توی وریفای کردن درخواست مشکل دارم.
سوال:
1- متد urlModify چیکار میکنه دقیقا؟! 
2- چرا اصلا کال بک یو آر ال بصورت پست فراخونی نمیشه؟ داخل روت گِت میره بجای پُست
2- مقادیر بازگشت داده شده از سمت بانک رو بشکل زیر میگیرم اما نال هستن:
```php
$status = Input::get('status');
$trackingCode = Input::get('transId');
```

**Comment by hpakdaman** [comment]
سلام .

۱-  این متد یکسری کويری استرینگ رو به یوآرال اضافه میکنه
۲- دلیل اینه که بعضی از بانک ها با گت ارسال میکنن بعضی از بانک ها با پست  به ناچار مجبور شدیم از  متد انی استفاده کنیم
متد any
۳- احتمالا یه اشتباه میکنید . مستندات بانک رو بخونید . و بجای 
input
از 
Request
استفاده نمایید
