### ISSUE TITLE
پرداخت مجدد رکوردی که پرداخت نشده است

### ISSUE THREAD

**Issue by ilbeygi** [larabook/gateway#72]
سلام
بنده میخوام یک لیست فاکتور درست کنم مثلا رکوردهایی ک ناموفق بودن رو دوباره بشه پرداخت کرد ، میشه راهنمایی کنید ک چطور باید این کار رو انجام بدم؟
با همین جدوالای خوده پکیج اگه چندتا فیلد یوزر ایدی و .. اضافه کنم میشه این کار رو انجام داد یا باید یک جدول دیگه درست کنم؟
سپاس

**Comment by hpakdaman** [comment]
با سلام . 
بله میشه . کافیه مبلغ فاکتور رو بفرستید تا پرداخت بشه
