### ISSUE TITLE
درگاه شرکت مبنا کارت آریا

### ISSUE THREAD

**Issue by mohammadlom** [larabook/gateway#74]
با سلام
آیا این پکیج به درگاه شرکت مبناکارت آریا نیز متصل می شود یا خیر؟
کداین درگاه رو که بررسی کردم برای پی اچ پی تفاوت زیادی با درگاه های دیگه نداشت
میخواستم ببینم این پکیج نیز برای این دستگاه کار میکند یا خیر!

**Comment by hpakdaman** [comment]
با سلام . قرارداد جدیدی با بانک صادرات (شرکت مبنا کارت آریا ) منعقد شده که قرار هست درگاه اتصال به بانک صادرات را به صورت یک پکیج مجزا پیاده سازی کنیم . انشالله پس از اتمام از طریق وب سایت لارابوک اطلاع رسانی خواهد شد.
موفق باشید
