### ISSUE TITLE
ارورر علت : SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl' : failed to load external entity "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"

### ISSUE THREAD

**Issue by masoudsourni** [larabook/gateway#75]
سلام بعد از ۱ سال کار کردن با این پکیج  بر روی سایت  http://www.shop-intex.com امروز با این اررور مواجعه شدم ؟
: SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl' : failed to load external entity "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"

**Comment by hpakdaman** [comment]
سلان. این مشکل بانک ملت هست بزودی حل میشه . مشکل درگاه نیست

**Comment by saber13812002** [comment]
این خطوط رو جایگزین کنید حل میشه

		try {
			$context = stream_context_create(
				[
					'ssl' => array(
						'verify_peer'       => false,
						'verify_peer_name'  => false
					)
				]
			);

			$soap = new SoapClient($this->serverUrl,  [
				'stream_context' => $context
			]);

			//$soap = new \SoapClient($this->serverUrl);
