### ISSUE TITLE
Cannot insert explicit value for identity column in table 'gateway_transactions' 

### ISSUE THREAD

**Issue by saeedizade** [larabook/gateway#76]
از Microsoft Sql server
 استفاده میکنم موقع اضافه کردن این ارور رو میده

SQLSTATE[23000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Cannot insert explicit value for identity column in table 'gateway_transactions' when IDENTITY_INSERT is set to OFF. (SQL: insert into [gateway_transactions] ([id], [port], [price], [status], [ip], [created_at], [updated_at]) values (150272300069, ZARINPAL, 100, INIT, ::1, 2017-08-14 19:33:20.000, 2017-08-14 19:33:20.000))

وقتی روی mysql
 تست میکنم درسته اما مجبورم به دلایلی از
 sqlserv
 استفاده کنم کسی میدونه چی کار کنم؟

**Comment by saeedizade** [comment]
باید قبل تراکنش بزنم ::
    DB::statement('SET IDENTITY_INSERT gateway_transactions ON');
توی کنسول اس کیول سرور میشه بعد این به دیتابیس اد کزد اما کجا داخل لاراول بزنم هیشه قبلش اجازه بده

**Comment by hpakdaman** [comment]
متاسفانه در مورد اسکیول سرور اطلاعی نداریم .
