### ISSUE TITLE
Error Code #41 / شماره درخواست تکراری

### ISSUE THREAD

**Issue by a-gholami** [larabook/gateway#78]
سلام توی تست به یک مشکل برخوردم که هنگام اتصال به درگاه بانک ملت خطای 41 (شماره درخواست تکراری) هست رو میداد البته کد (آی دی ) برای رکورد جدول بصورت یکتا بر حسب زمان ایجاد میشد ولی دقیق نفهمیدم چرا این خطا را میده در هر صورت به روش زیر خطا رو رفع کردم گفتم یه بررسی هم خودتون بفرمایید
البته با سایت زیر تست کردم ( سایت مخصوص تست درگاه های بانکی در محیط دولوپ هست ) 
http://banktest.ir

[ROOT]\vendor\larabook\gateway\src\PortAbstract.php 
Code Line 191
`function getTimeId()
	{
		$genuid = function(){
			return substr(str_pad(str_replace('.','', microtime(true)),12,0),0,12);
		};
		$uid=$genuid();
		while ($this->getTable()->whereId($uid)->first())
			$uid = $genuid();
		return $uid;
	}`
( Edited )
`function getTimeId()
	{
		$genuid = function(){
			return time();
		};
		$uid=$genuid();
		while ($this->getTable()->whereId($uid)->exists()){
		    sleep(0.5);
            $uid = $genuid();
        }
		return $uid;
	}`
Laravel -v : 5.4
PHP -v : 7

**Comment by hpakdaman** [comment]
با سلام  . 

متاسفانه با بانک تست کار نکردیم احتمالا با این سیستم سازگار نیست که این خطا روی میدهد

**Comment by saber13812002** [comment]
مشکل اصلا ربطی به بانک تست نداره با خود بانک ملی هم من این مشکل رو داشتم

با این تکه کدی که ایشون آدرس داده مشکل من حل شد

ممنونم از ایشون

ای کاش توضیح میدادن چه شکلی متوجه شدن که این اتفاق بخاطر این تابع است

و یک توضیحی هم بدن که چطوری این مشکل رو حل کردن با چه منطقی؟

laravel version : 5.8

PHP version 7.2

**Comment by iamtartan** [comment]
@a-gholami عزیز سلام
من تکه کدی که تو سایت بانک تست خطای ۴۱ رو تولید میکنه اینجا میذارم که همگی متوجه سادگی قضیه بشین.

```php
// check for duplicate order id
$previousTransaction = Mellat::where('terminal_id', $terminalId)
    ->where('order_id', $orderId)
    ->first();

if ($previousTransaction) {
    $r->return = "41,{$refId}"; //duplicate order_id
    break;
}
```

همونطور که میبینید یه کوئری ساده اس که موقع دریافت درخواست شما با شناسه ترمینتال و شماره سفارش شما یه کوئری تو جدول تراکنهشای بانک ملت زده میشه که اگه موردی وجود داشت خطای ۴۱ برگدونده بشه و اگه نه فرایند ادامه پیدا کنه. هیچ مورد عجیب و نامفهمومی داخلش نیست. حالا چه موردی هست که شما به این مشکل برخوردید باید دقیقتر بررسی کنید.

Larapay اگه دنبال یه پکیج لاراول هماهنگ با بانک تست میگردی میتونی پکیج خود من رو استفاده کنی که اسمش هست 
تقریبا مشابه پکیج حامد هستش اما تو محیط تست با بانک تست کار میکنه
[https://github.com/iamtartan/laravel-online-payment](https://github.com/iamtartan/laravel-online-payment)`
@saber13812002 ممنون از صابر که مشکل رو به من خبر دادن که راهنمایی کنم
