### ISSUE TITLE
برگرداندن ویو به جای اسکپشن خطا

### ISSUE THREAD

**Issue by ilbeygi** [larabook/gateway#80]
با سلام و خسته نباشید
وقتی ز بانک مشکلی پیش میاد و کاربر بر میگرده میخوام جای خطایی که نشون میده یک ویو با یک استابیل نشون بده ولی نمیدونم چطوره
ممنون میشم اگه راهنمایی کنید
بنده از یک همچین کدی استفاده کردم ولی درست نشد
`catch (Exception $e) {
                $mess = $e->getMessage();
                return view('pages.callback',compact('mess'));
            }`

سپاس

**Comment by hpakdaman** [comment]
پشت اکسپشن بک اسلش بزارید به این صورت :  
catch (**\**Exception $e)
