### ISSUE TITLE
پرداخت از حساب زرین پال

### ISSUE THREAD

**Issue by mGolestan** [larabook/gateway#81]
سلام.
توی حالت اولیه پکیج اگر سایتی درگاه زرین پالش رو برای پرداخت انتخاب کرده باشه و پرداخت کننده بخواد از کیف پول زرین پالش مبلغ رو پرداخت کنه توی کال بک از بانک به مشکل بر میخوره. چون که با این حالت شماره حسابی رو وارد نکرده و توی تابع کال بک، شماره حساب میخواد گرفته شه و کد های بعد از اون ران نمیشه
این در حالت دیفالت پکیج هست

           try {
                $gateway = \Gateway::verify();
                $trackingCode = $gateway->trackingCode();
                $refId = $gateway->refId();
                $cardNumber = $gateway->cardNumber();

                //درستورات اینجا انجام نمیشوند با در نظر گرفتن حالت بالا
                
            } catch (Exception $e) {

                echo $e->getMessage();
            }
‍‍

که با در نظر گرفتن حالتی که بالا گفتم باید به صورت زیر اپدیت شه

            try {
                $gateway = \Gateway::verify();
                $trackingCode = $gateway->trackingCode();
                $refId = $gateway->refId();
                try {
                    $cardNumber = $gateway->cardNumber();
                } finally {

                    // در انجا دستورات انجام میشوند
                   
                }
            } catch (Exception $e) {

                echo $e->getMessage();
            }

موفق باشید

**Comment by hpakdaman** [comment]
با سلام . 
کد ها چک شد .
در صورتی که شماره کارت موجود نباشد این قسمت اکسپشنی تولید نمیکند . 
نیاز به نوشتن 
try
نیست

بجای آن از از شرط استفاده کنید : 
` $cardNumber = $gateway->cardNumber();
if($cardNumber){
 // do some things ...
}
`
