### ISSUE TITLE
مقدار دهی به فیلدهای دلخواه

### ISSUE THREAD

**Issue by m-alinasab** [larabook/gateway#82]
سلام ، وقت بخیر و تشکر بابت پکیج خیلی خوب و مفیدتون .
یه سوالی داشتم در همین مورد :
من جدول مربوط به فاکتورها رو کمی شخصی سازی کردم و چندتا فیلد بهش اضافه کردم ، حالا میخوام زمانی داره یه فاکتور جدید ایجاد میکنه ، مقدار فیلدهایی که خودم اضافه کردم رو هم پر کنم

روشی برای این کار هست ؟

تو مستندات چیزی پیدا نکردم !

**Comment by askariweb** [comment]
سلام
این سوالات مربوط به خود لاراول هست نه پکیج درگاه.
لاراول رو شخصی سازی کنید.

**Comment by m-alinasab** [comment]
ممنون از شما

مشکل برطرف شد 
نباید پکیج شمارو دستکاری میکردم و تنها با همون ref_id باید کارهامو انجام بدم

Sent from Mail for Windows 10

**Comment by hpakdaman** [comment]
در خصوص دستکاری فیلد ها قبل از ارسال به بانک این دوستمون پرسیده بودن من پاسخ دادم شاید بتونه کمکتون کنه : 


[https://github.com/larabook/gateway/issues/97](url)
