### ISSUE TITLE
اضافه کردن یک Foreign key به تیبل

### ISSUE THREAD

**Issue by MostafaNobaghi** [larabook/gateway#97]
من توی جدول 
gateway_transactions
 یه ستون جدید اضافه کردم به اسم 
receipt_id
 که مشخص کننده فاکتور مربوط به این پرداخت هست، چجوری میتونم این آیدی رو به متد زرین پال پاس بدم که توی دیتا بیس ذخیره کنه؟

**Comment by hpakdaman** [comment]
به کد های سری جدید نگاه کنید به راحتی میتونید این عمل رو انجام بدید .

**Comment by hpakdaman** [comment]
try {
   
   $gateway = \Gateway::make(new \Mellat());

    $gateway
        ->price(1000)
         ->ready();

   $refId =  $gateway->refId(); // شماره ارجاع بانک
   $transID = $gateway->transactionId(); // شماره تراکنش

  // در اینجا
  //  شماره تراکنش  بانک را با توجه به نوع ساختار دیتابیس تان 
  //  در جداول مورد نیاز و بسته به نیاز سیستم تان
  // ذخیر کنید .
  
   return $gateway->redirect();
   
} catch (\Exception $e) {
   
   	echo $e->getMessage();
}
