### ISSUE TITLE
php artisan vendor:publish for laravel 5.5

### ISSUE THREAD

**Issue by miadz** [larabook/gateway#98]
please change this 
php artisan vendor:publish --provider=Larabookir\Gateway\GatewayServiceProvider

to this
php artisan vendor:publish --provider="Larabookir\Gateway\GatewayServiceProvider"

**Comment by sobhanattar** [comment]
@miadz this issue is resolved in their guide in their [website](http://larabook.ir/%D8%A7%D8%AA%D8%B5%D8%A7%D9%84-%D8%AF%D8%B1%DA%AF%D8%A7%D9%87-%D8%A8%D8%A7%D9%86%DA%A9-%D9%84%D8%A7%D8%B1%D8%A7%D9%88%D9%84/). and I propose a file change on their readme.me

**Comment by HassanShojaei** [comment]
@miadz Thanks you saved my day
