### ISSUE TITLE
ارور عجیب موقع اتصال به درگاه

### ISSUE THREAD

**Issue by ikosar** [larabook/gateway#99]
`   "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'where `id` = ? limit 1' at line 1 (SQL: select * where `id` = 151654692732 limit 1)",`

**Comment by ikosar** [comment]
درگاه ملت هست

**Comment by ali-pedram** [comment]
run this command : php artisan config:clear

**Comment by HassanShojaei** [comment]
Hi I have same issue two!
And didn't get fixed by config:clear artisan command!
Also when I use php artisan migrate this will not create any tables in database!

**Comment by ikosar** [comment]
This Problem fixed By Using Publish Command By " "
php artisan vendor:publish --provider="Larabookir\Gateway\GatewayServiceProvider"
instead of 
php artisan vendor:publish --provider=Larabookir\Gateway\GatewayServiceProvider
